export interface TestimonialType {
  id: string;
  name: string;
  initials: string;
  location: string;
  rating: number;
  service: string;
  content: string;
  image: string;
  verified: boolean;
}

export const testimonialsData: Record<string, TestimonialType[]> = {
  "default": [
    {
      id: "def-1",
      name: "Sarah Mitchell",
      initials: "SM",
      location: "Dobson Ranch, Chandler",
      rating: 5,
      service: "Full Bathroom Remodel",
      content: "Alex and his team at ARZ were fantastic. Our old bathroom in Dobson Ranch was just collecting dust. They converted it into a beautiful modern space. Truly the best bathroom remodeling contractor in Chandler.",
      image: "/images/testimonials/t1.avif",
      verified: true,
    },
    {
      id: "def-2",
      name: "James Peterson",
      initials: "JP",
      location: "Ocotillo, Chandler",
      rating: 5,
      service: "Master Bath Renovation",
      content: "A full master bath remodel is usually a nightmare, but ARZ made it easy. They handled everything from the permits with the City of Chandler to the final tile grout. The project stayed right on budget.",
      image: "/images/testimonials/t2.avif",
      verified: true,
    },
    {
      id: "def-3",
      name: "Maria Hernandez",
      initials: "MH",
      location: "Fulton Ranch, Chandler",
      rating: 5,
      service: "Bathroom Upgrade",
      content: "I was worried about the Arizona heat affecting the grout, but Alex explained their process and materials in detail. The tile work is flawless. It's rare to find a contractor who actually shows up when they say they will!",
      image: "/images/testimonials/t7.avif",
      verified: true,
    }
  ],
  "bathroom-remodeling": [
    {
      id: "br-1",
      name: "Rebecca Larson",
      initials: "RL",
      location: "Cooper Commons, Chandler",
      rating: 5,
      service: "Master Bathroom Remodeling",
      content: "The transformation of our master bathroom is unbelievable. ARZ completely gutted the old space and installed a stunning double vanity and a massive walk-in shower. Their crew was professional, kept the house clean, and finished right on schedule.",
      image: "/images/testimonials/t3.avif",
      verified: true,
    },
    {
      id: "br-2",
      name: "David & Lisa Chen",
      initials: "DC",
      location: "Sun Lakes, AZ",
      rating: 5,
      service: "Complete Renovation",
      content: "We hired ARZ for a complete overhaul of our 1990s bathroom. From the 3D design phase to the final plumbing fixtures, everything was top-notch. They really listened to what we wanted and delivered a luxurious, modern bathroom.",
      image: "/images/testimonials/t12.avif",
      verified: true,
    },
    {
      id: "br-3",
      name: "Michael Thompson",
      initials: "MT",
      location: "Downtown Chandler",
      rating: 5,
      service: "Bathroom Renovation",
      content: "Excellent communication from start to finish. They handled all the plumbing relocation and electrical upgrades without a hitch. The new lighting and custom tile work added so much value to our home. Highly recommended!",
      image: "/images/testimonials/t4.avif",
      verified: true,
    }
  ],
  "shower-remodeling": [
    {
      id: "sr-1",
      name: "Jessica Alvarez",
      initials: "JA",
      location: "Ahwatukee, Phoenix",
      rating: 5,
      service: "Walk-in Shower Remodel",
      content: "We wanted to rip out our unused fiberglass tub and replace it with a sleek walk-in shower. ARZ used Schluter waterproofing and frameless glass, and the result is like a spa. Best shower remodeling company we've worked with.",
      image: "/images/testimonials/t5.avif",
      verified: true,
    },
    {
      id: "sr-2",
      name: "Thomas Wright",
      initials: "TW",
      location: "Gilbert, AZ",
      rating: 5,
      service: "Shower Expansion & Tile",
      content: "Alex's team expanded our tiny shower into a huge double-head shower enclosure. The tile work is absolutely perfect, down to the custom niches. They were respectful of our home and the dust was kept to an absolute minimum.",
      image: "/images/testimonials/t6.avif",
      verified: true,
    },
    {
      id: "sr-3",
      name: "Emily Davies",
      initials: "ED",
      location: "Ocotillo, Chandler",
      rating: 5,
      service: "Custom Shower Design",
      content: "Our old shower was leaking behind the walls. Alex caught the structural damage and fixed it properly before tiling. Now we have a beautiful, leak-proof shower with premium fixtures. Very honest and professional team.",
      image: "/images/testimonials/t9.avif",
      verified: true,
    },
    {
      id: "sr-4",
      name: "Patricia Gonzalez",
      initials: "PG",
      location: "Fulton Ranch, Chandler",
      rating: 5,
      service: "Master Shower Remodel",
      content: "I had the hardest time finding someone to handle our master shower properly. ARZ understood our vision immediately—we wanted a spa-like feel with Schluter waterproofing and rainfall showerhead. The execution was flawless. They really know their craft.",
      image: "/images/testimonials/t11.avif",
      verified: true,
    },
    {
      id: "sr-5",
      name: "Richard Foster",
      initials: "RF",
      location: "Sun Lakes, Chandler",
      rating: 5,
      service: "Frameless Glass & Tile Installation",
      content: "We upgraded from a builder-grade shower to a frameless glass enclosure with porcelain tile. The attention to detail was incredible—every edge is perfect, every seal is tight. My wife keeps saying it feels like we're at a hotel every morning.",
      image: "/images/testimonials/t8.avif",
      verified: true,
    }
  ],
  "bathtub-remodeling": [
    {
      id: "bt-1",
      name: "Robert Hughes",
      initials: "RH",
      location: "Mesa, AZ",
      rating: 5,
      service: "Bathtub Replacement",
      content: "We needed our old, stained bathtub replaced quickly before family arrived. ARZ gave us a fair price and swapped it out for a beautiful acrylic soaking tub in just a couple of days. The new surround looks amazing.",
      image: "/images/testimonials/t10.avif",
      verified: true,
    },
    {
      id: "bt-2",
      name: "Samantha Brooks",
      initials: "SB",
      location: "San Marcos, Chandler",
      rating: 5,
      service: "Tub & Surround Upgrade",
      content: "I love my new deep soaking tub! The installers were so polite and made sure everything was perfectly caulked and sealed. It completely updated the look of our guest bathroom without breaking the bank.",
      image: "/images/testimonials/t1.avif",
      verified: true,
    },
    {
      id: "bt-3",
      name: "Kevin Patel",
      initials: "KP",
      location: "South Tempe, AZ",
      rating: 5,
      service: "Bathtub Remodel",
      content: "The quality of work on our bathtub remodel exceeded my expectations. They removed the cast iron tub carefully without damaging the floor, and the new installation is sturdy and gorgeous. Great attention to detail.",
      image: "/images/testimonials/t8.avif",
      verified: true,
    }
  ],
  "tub-to-shower-conversion": [
    {
      id: "tsc-1",
      name: "William Foster",
      initials: "WF",
      location: "Sun Lakes, Chandler",
      rating: 5,
      service: "Tub to Walk-in Shower",
      content: "As we get older, stepping over the tub was becoming dangerous. ARZ converted our tub into a low-threshold walk-in shower with grab bars and a bench. We feel so much safer now. Highly recommend for seniors.",
      image: "/images/testimonials/t2.avif",
      verified: true,
    },
    {
      id: "tsc-2",
      name: "Amanda Jenkins",
      initials: "AJ",
      location: "Queen Creek, AZ",
      rating: 5,
      service: "Tub-to-Shower Conversion",
      content: "Our garden tub was a massive waste of space. The team removed it and built a stunning frameless glass shower in its place. The whole process was smooth, and the bathroom feels twice as big now!",
      image: "/images/testimonials/t7.avif",
      verified: true,
    },
    {
      id: "tsc-3",
      name: "Christopher Lee",
      initials: "CL",
      location: "Fulton Ranch, Chandler",
      rating: 5,
      service: "Tub Conversion",
      content: "I received three quotes, and ARZ was the most knowledgeable about proper waterproofing techniques. The tub-to-shower conversion took exactly as long as they promised, and there were no hidden fees. Fantastic experience.",
      image: "/images/testimonials/t11.avif",
      verified: true,
    }
  ],
  "bathroom-tile-installation": [
    {
      id: "ti-1",
      name: "Olivia Martinez",
      initials: "OM",
      location: "Dobson Ranch, Chandler",
      rating: 5,
      service: "Bathroom Floor & Wall Tile",
      content: "The tile installation in our bathroom is a work of art. They aligned every grout line perfectly and helped us choose a non-slip porcelain tile that looks like natural stone. You can tell they are true craftsmen.",
      image: "/images/testimonials/t5.avif",
      verified: true,
    },
    {
      id: "ti-2",
      name: "Daniel Harris",
      initials: "DH",
      location: "Ahwatukee, AZ",
      rating: 5,
      service: "Custom Tile Shower",
      content: "We had a complex mosaic tile design in mind, and the ARZ team executed it flawlessly. They used high-quality epoxy grout so we don't have to worry about stains. The attention to detail is just incredible.",
      image: "/images/testimonials/t4.avif",
      verified: true,
    },
    {
      id: "ti-3",
      name: "Sophia Nguyen",
      initials: "SN",
      location: "Gilbert, AZ",
      rating: 5,
      service: "Tile Flooring Upgrade",
      content: "They ripped out our old linoleum and installed beautiful large-format tile. The floors are perfectly level and it completely changed the feel of the bathroom. The crew cleaned up thoroughly every single day.",
      image: "/images/testimonials/t9.avif",
      verified: true,
    }
  ],
  "walk-in-showers": [
    {
      id: "wis-1",
      name: "Richard & Mary Stone",
      initials: "RS",
      location: "Sun Lakes, AZ",
      rating: 5,
      service: "Curbless Walk-in Shower",
      content: "We needed an accessible solution for my husband's wheelchair. ARZ built a beautiful curbless walk-in shower that looks like it belongs in a luxury hotel, not a hospital. The drainage works perfectly and it's given us our independence back.",
      image: "/images/testimonials/t12.avif",
      verified: true,
    },
    {
      id: "wis-2",
      name: "Brian Cooper",
      initials: "BC",
      location: "Ocotillo, Chandler",
      rating: 5,
      service: "Walk-in Shower Remodel",
      content: "I wanted a modern, minimalist walk-in shower with no door to clean. Alex designed a layout that keeps the water completely contained. The rainfall showerhead and custom bench make every morning feel like a spa visit.",
      image: "/images/testimonials/t6.avif",
      verified: true,
    },
    {
      id: "wis-3",
      name: "Laura Bennett",
      initials: "LB",
      location: "Mesa, AZ",
      rating: 5,
      service: "Walk-in Shower Installation",
      content: "From the initial consultation to the final polish of the glass, ARZ was professional and communicative. The new walk-in shower is gorgeous and so much easier to maintain than our old tub. Highly recommend!",
      image: "/images/testimonials/t1.avif",
      verified: true,
    }
  ],
  "ada-bathroom-remodeling": [
    {
      id: "ada-1",
      name: "Arthur Pendelton",
      initials: "AP",
      location: "Sun Lakes, Chandler",
      rating: 5,
      service: "ADA Accessibility Remodel",
      content: "Alex and his crew converted our guest bathroom into an ADA-compliant space. The curbless shower and grab bars were installed perfectly. They really understand local building codes and senior-safe designs.",
      image: "/images/testimonials/t2.avif",
      verified: true,
    },
    {
      id: "ada-2",
      name: "Helen Vance",
      initials: "HV",
      location: "Fulton Ranch, Chandler",
      rating: 5,
      service: "Walk-in Safety Shower",
      content: "We needed grab bars and non-slip mosaic tile installed for my father's independence. ARZ did a flawless job, keeping the bathroom beautiful and incredibly safe. Excellent, clean installation.",
      image: "/images/testimonials/t9.avif",
      verified: true,
    }
  ],
  "bathroom-flooring-installation": [
    {
      id: "bf-1",
      name: "Douglas Miller",
      initials: "DM",
      location: "Warner Ranch, Chandler",
      rating: 5,
      service: "Bathroom Flooring Installation",
      content: "They installed wood-look plank tile across our entire master bathroom floor. The level layout is absolutely perfect, and they handled the concrete subfloor preparation with great care.",
      image: "/images/testimonials/t8.avif",
      verified: true,
    },
    {
      id: "bf-2",
      name: "Karen Jenkins",
      initials: "KJ",
      location: "Dobson Ranch, Chandler",
      rating: 5,
      service: "Porcelain Flooring",
      content: "We replaced our old vinyl with large-format porcelain tiles. Fewer grout lines make the floor so much easier to clean, and it looks extremely modern. Fast, professional work.",
      image: "/images/testimonials/t12.avif",
      verified: true,
    }
  ],
  "bathroom-lighting-installation": [
    {
      id: "bl-1",
      name: "Gary Fletcher",
      initials: "GF",
      location: "Kyrene Corridor, Chandler",
      rating: 5,
      service: "Bathroom Lighting & Electrical",
      content: "ARZ added recessed LED downlights and vanity sconces to our dark guest bath. They ran new GFCI circuits and smart switches. Shadow-free light makes a massive difference every morning.",
      image: "/images/testimonials/t4.avif",
      verified: true,
    },
    {
      id: "bl-2",
      name: "Diana Ross",
      initials: "DR",
      location: "Gila Springs, Chandler",
      rating: 5,
      service: "Vapor-Proof LED Upgrade",
      content: "They installed dedicated wiring and wet-zone vapor-proof fixtures inside our custom shower. Everything was clean, code-compliant, and done in one day.",
      image: "/images/testimonials/t5.avif",
      verified: true,
    }
  ],
  "bathroom-vanity-installation": [
    {
      id: "bvi-1",
      name: "Steven Vance",
      initials: "SV",
      location: "Clemente Ranch, Chandler",
      rating: 5,
      service: "Vanity Replacement",
      content: "Our custom double vanity with quartz countertops is beautiful. The leveling and shimming were done with surgical precision, so the drawers glide perfectly. Exceptional craftsmanship.",
      image: "/images/testimonials/t6.avif",
      verified: true,
    },
    {
      id: "bvi-2",
      name: "Nancy Cooper",
      initials: "NC",
      location: "Cooper Commons, Chandler",
      rating: 5,
      service: "Cabinetry & Countertop Installation",
      content: "We replaced our old vanity with a floating custom cabinet set. ARZ helped us pick a gorgeous quartz slab and handled the entire plumbing hookup smoothly.",
      image: "/images/testimonials/t10.avif",
      verified: true,
    }
  ],
  "cabinet-countertop-installation": [
    {
      id: "cci-1",
      name: "Mark Reynolds",
      initials: "MR",
      location: "Ocotillo, Chandler",
      rating: 5,
      service: "Quartz Countertop Installation",
      content: "Alex helped us source custom quartz slabs from a local showroom and handled the fabrication and installation. Seams are practically invisible, and the support brackets are rock-solid.",
      image: "/images/testimonials/t8.avif",
      verified: true,
    },
    {
      id: "cci-2",
      name: "Janice Long",
      initials: "JL",
      location: "Fox Crossing, Chandler",
      rating: 5,
      service: "Custom Cabinets & Countertops",
      content: "Stunning craftsmanship on our bathroom cabinets and quartz tops. The plumbing lines were realigned beautifully, and the finish looks extremely premium.",
      image: "/images/testimonials/t11.avif",
      verified: true,
    }
  ],
  "guest-bathroom-remodeling": [
    {
      id: "gbr-1",
      name: "Arthur Hayes",
      initials: "AH",
      location: "Fulton Ranch, Chandler",
      rating: 5,
      service: "Guest Bath Remodeling",
      content: "We upgraded our guest bath with a new vanity, toilet, and tile shower surround. The team was fast, clean, and completed the entire job in less than two weeks.",
      image: "/images/testimonials/t7.avif",
      verified: true,
    },
    {
      id: "gbr-2",
      name: "Melissa Vance",
      initials: "MV",
      location: "Dobson Ranch, Chandler",
      rating: 5,
      service: "Guest Bathroom Renovation",
      content: "A beautiful, quick refresh for our guest bathroom. The plumbing upgrades and custom shelving make the small space highly functional. Our guests love it.",
      image: "/images/testimonials/t3.avif",
      verified: true,
    }
  ],
  "luxury-bathroom-remodeling": [
    {
      id: "lbr-1",
      name: "Geraldine Vance",
      initials: "GV",
      location: "Ocotillo, Chandler",
      rating: 5,
      service: "Luxury Master Suite Remodel",
      content: "Our master bathroom is now a luxury oasis. The freestanding tub, custom curbless shower with linear drain, and heated floors are incredible. Pure luxury and impeccable attention to detail.",
      image: "/images/testimonials/t12.avif",
      verified: true,
    },
    {
      id: "lbr-2",
      name: "Phillip Vance",
      initials: "PV",
      location: "Fulton Ranch, Chandler",
      rating: 5,
      service: "Master Bath Oasis",
      content: "High-end finishes, custom dual vanities, and frameless glass panels. ARZ was outstanding, managing the permits and engineering perfectly. Worth every penny.",
      image: "/images/testimonials/t2.avif",
      verified: true,
    }
  ],
  "shower-bathtub-upgrade": [
    {
      id: "sbu-1",
      name: "Victor Stone",
      initials: "VS",
      location: "Sun Lakes, Chandler",
      rating: 5,
      service: "Tub & Shower Upgrade",
      content: "We replaced our outdated tub surround and upgraded the valve systems. The leak-proof backing and clean tile work make the bathroom look brand new. Excellent service.",
      image: "/images/testimonials/t1.avif",
      verified: true,
    },
    {
      id: "sbu-2",
      name: "Cynthia Ross",
      initials: "CR",
      location: "Warner Ranch, Chandler",
      rating: 5,
      service: "Shower-Tub Combo Upgrade",
      content: "They removed the old fiberglass surround and built a gorgeous custom tile wall over a new soaking tub. No more leaks or mold issues. Very happy with their work.",
      image: "/images/testimonials/t9.avif",
      verified: true,
    }
  ],
  "shower-replacement": [
    {
      id: "sr-rep-1",
      name: "Daniel Miller",
      initials: "DM",
      location: "Dobson Ranch, Chandler",
      rating: 5,
      service: "Shower Replacement",
      content: "Our old shower was leaking behind the plaster. ARZ demolished it, repaired the wood framing, and installed a clean porcelain tile shower with Schluter waterproofing. Superb execution.",
      image: "/images/testimonials/t5.avif",
      verified: true,
    },
    {
      id: "sr-rep-2",
      name: "Sandra Jenkins",
      initials: "SJ",
      location: "Ocotillo, Chandler",
      rating: 5,
      service: "New Shower Installation",
      content: "We replaced our plastic enclosure with custom tile and frameless glass. It completely transformed the room. Excellent communication and a highly professional crew.",
      image: "/images/testimonials/t6.avif",
      verified: true,
    }
  ],
  "small-bathroom-remodeling": [
    {
      id: "sbr-1",
      name: "Laura Miller",
      initials: "LM",
      location: "Downtown Chandler",
      rating: 5,
      service: "Small Bathroom Renovation",
      content: "They transformed our cramped powder room with a floating vanity and recessed storage. The space feels twice as large now. Outstanding design solutions.",
      image: "/images/testimonials/t1.avif",
      verified: true,
    },
    {
      id: "sbr-2",
      name: "Kevin Harris",
      initials: "KH",
      location: "Cooper Commons, Chandler",
      rating: 5,
      service: "Space Optimization",
      content: "Smart layout updates and recessed medicine cabinets saved so much room. Large format tiles on the walls made it look much wider. Clean and professional.",
      image: "/images/testimonials/t3.avif",
      verified: true,
    }
  ],
  "tub-removal": [
    {
      id: "tr-1",
      name: "William Wright",
      initials: "WW",
      location: "Sun Lakes, Chandler",
      rating: 5,
      service: "Cast Iron Tub Removal",
      content: "Removing the heavy cast iron tub looked impossible, but ARZ extracted it carefully without any structural or drywall damage. They prepared the plumbing drain lines perfectly.",
      image: "/images/testimonials/t2.avif",
      verified: true,
    },
    {
      id: "tr-2",
      name: "Sandra Brooks",
      initials: "SB",
      location: "Ocotillo, Chandler",
      rating: 5,
      service: "Tub Extraction & Prep",
      content: "Professional, fast extraction of our old garden tub. They repaired the drywall and prepared the floor substrate for the next renovation stage. Very clean.",
      image: "/images/testimonials/t7.avif",
      verified: true,
    }
  ]
};

export function getTestimonials(category?: string): TestimonialType[] {
  if (category && testimonialsData[category]) {
    return testimonialsData[category];
  }
  return testimonialsData["default"];
}
